#!/usr/bin/env bash

set -eu

SIMDIR="simul"
GHDLFLAGS="--ieee=standard -fsynopsys --warn-no-vital-generic --workdir=$SIMDIR"

COMPONENT="$1"
SIMBIN=$COMPONENT"_tb"
TESTFILES=testbench/$COMPONENT"_tb.vhdl"

if [[ "$COMPONENT" == "main" ]]; then
	SRCFILES="src/main.vhdl
		  src/main_control.vhdl
		  src/angle_generator.vhdl
		  src/rotator_3d.vhdl
		  src/plot_generator.vhdl
		  src/console.vhdl
		  src/io/up_down_counter.vhdl
		  src/io/uart/uart_tx.vhdl
		  src/io/uart/transmitter.vhdl
		  src/io/uart/time_generator.vhdl
		  src/io/vga/vga_sync.vhdl
		  src/io/vga/pixel_generator.vhdl
		  src/cordic/cordic.vhdl
		  src/cordic/adder.vhdl
		  src/cordic/register_mem.vhdl
		  src/cordic/shifter.vhdl
		  src/cordic/cordic_motor.vhdl
		  src/cordic/pre_processing.vhdl
		  src/cordic/post_processing.vhdl
		  src/plot/axes.vhdl
		  src/plot/vector.vhdl
		  src/plot/line_plotter.vhdl
		  src/plot/plot_control.vhdl
		  src/plot/vector_drawer.vhdl
		  src/plot/vector_eraser.vhdl
		  src/plot/coordinate_to_pixel.vhdl
		  src/plot/coordinate_to_vector.vhdl"
elif [[ "$COMPONENT" == "main_control" ]]; then
	SRCFILES="src/main_control.vhdl"
elif [[ "$COMPONENT" == "console" ]]; then
	SRCFILES="src/console.vhdl
		  src/io/uart/uart_tx.vhdl
		  src/io/uart/transmitter.vhdl
		  src/io/uart/time_generator.vhdl"
elif [[ "$COMPONENT" == "angle_generator" ]]; then
	SRCFILES="src/angle_generator.vhdl
		  src/io/up_down_counter.vhdl
		  src/cordic/register_mem.vhdl"
elif [[ "$COMPONENT" == "plot_generator" ]]; then
	SRCFILES="src/plot_generator.vhdl
		  src/plot/axes.vhdl
		  src/plot/vector.vhdl
		  src/plot/line_plotter.vhdl
		  src/plot/plot_control.vhdl
		  src/plot/vector_drawer.vhdl
		  src/plot/vector_eraser.vhdl
		  src/plot/coordinate_to_pixel.vhdl
		  src/plot/coordinate_to_vector.vhdl
		  src/io/vga/vga_sync.vhdl
		  src/io/vga/pixel_generator.vhdl"
elif [[ "$COMPONENT" == "rotator_3d" ]]; then
	SRCFILES="src/rotator_3d.vhdl
		  src/cordic/cordic.vhdl
		  src/cordic/adder.vhdl
		  src/cordic/register_mem.vhdl
		  src/cordic/shifter.vhdl
		  src/cordic/cordic_motor.vhdl
		  src/cordic/pre_processing.vhdl
		  src/cordic/post_processing.vhdl"
elif [[ "$COMPONENT" == "vector" ]]; then
	SRCFILES="src/plot/vector.vhdl"
elif [[ "$COMPONENT" == "axes" ]]; then
	SRCFILES="src/plot/axes.vhdl"
elif [[ "$COMPONENT" == "vector_eraser" ]]; then
	SRCFILES="src/plot/vector_eraser.vhdl"
elif [[ "$COMPONENT" == "line_plotter" ]]; then
	SRCFILES="src/plot/line_plotter.vhdl"
elif [[ "$COMPONENT" == "vector_drawer" ]]; then
	SRCFILES="src/plot/line_plotter.vhdl
		  src/plot/vector_drawer.vhdl"
elif [[ "$COMPONENT" == "coordinate_to_pixel" ]]; then
	SRCFILES="src/plot/coordinate_to_pixel.vhdl"
elif [[ "$COMPONENT" == "coordinate_to_vector" ]]; then
	SRCFILES="src/plot/coordinate_to_pixel.vhdl
		  src/plot/line_plotter.vhdl
		  src/plot/vector_drawer.vhdl
		  src/plot/coordinate_to_vector.vhdl"
elif [[ "$COMPONENT" == "plot_control" ]]; then
	SRCFILES="src/plot/plot_control.vhdl"
elif [[ "$COMPONENT" == "pixel_generator" ]]; then
	SRCFILES="src/io/vga/pixel_generator.vhdl"
elif [[ "$COMPONENT" == "vga_sync" ]]; then
	SRCFILES="src/io/vga/vga_sync.vhdl"
elif [[ "$COMPONENT" == "transmitter" ]]; then
	SRCFILES="src/io/uart/transmitter.vhdl"
elif [[ "$COMPONENT" == "time_generator" ]]; then
	SRCFILES="src/io/uart/time_generator.vhdl"
elif [[ "$COMPONENT" == "uart_tx" ]]; then
	SRCFILES="src/io/uart/uart_tx.vhdl
		  src/io/uart/transmitter.vhdl
		  src/io/uart/time_generator.vhdl"
elif [[ "$COMPONENT" == "up_down_counter" ]]; then
	SRCFILES="src/io/up_down_counter.vhdl
		  src/cordic/register_mem.vhdl"
elif [[ "$COMPONENT" == "pre_processing" ]]; then
	SRCFILES="src/cordic/pre_processing.vhdl"
elif [[ "$COMPONENT" == "cordic" ]]; then
	SRCFILES="src/cordic/cordic.vhdl
		  src/cordic/adder.vhdl
		  src/cordic/register_mem.vhdl
		  src/cordic/shifter.vhdl
		  src/cordic/cordic_motor.vhdl
		  src/cordic/pre_processing.vhdl
		  src/cordic/post_processing.vhdl"
else
	echo "component not found"
	exit 1
fi;

mkdir -p $SIMDIR
ghdl -i $GHDLFLAGS --work=work $TESTFILES $SRCFILES
ghdl -m $GHDLFLAGS --work=work $SIMBIN
