#!/usr/bin/env bash

set -eu

SIMDIR="simul"
GHDLFLAGS="--ieee=standard -fsynopsys --warn-no-vital-generic --workdir=$SIMDIR"

COMPONENT="$1"
SIMBIN=$COMPONENT"_tb"
TESTFILES=testbench/$COMPONENT"_tb.vhdl"

if [[ "$COMPONENT" == "vector" ]]; then
	SRCFILES="src/plot/vector.vhdl"
elif [[ "$COMPONENT" == "axes" ]]; then
	SRCFILES="src/plot/axes.vhdl"
elif [[ "$COMPONENT" == "vector_eraser" ]]; then
	SRCFILES="src/plot/vector_eraser.vhdl"
elif [[ "$COMPONENT" == "pixel_generator" ]]; then
	SRCFILES="src/io/vga/pixel_generator.vhdl"
elif [[ "$COMPONENT" == "vga_sync" ]]; then
	SRCFILES="src/io/vga/vga_sync.vhdl"
elif [[ "$COMPONENT" == "line_drawer" ]]; then
	SRCFILES="src/plot/line_drawer.vhdl"
elif [[ "$COMPONENT" == "vector_drawer" ]]; then
	SRCFILES="src/plot/vector_drawer.vhdl"
elif [[ "$COMPONENT" == "coordinate_to_pixel" ]]; then
	SRCFILES="src/plot/coordinate_to_pixel.vhdl"
else
	SRCFILES="src/$COMPONENT/cordic.vhdl src/$COMPONENT/adder.vhdl src/$COMPONENT/register_mem.vhdl src/$COMPONENT/shifter.vhdl src/$COMPONENT/cordic_motor.vhdl src/$COMPONENT/pre_processing.vhdl src/$COMPONENT/post_processing.vhdl"
fi;

STOPTIME="$2"
SIMFLAGS="--stop-time=$STOPTIME --vcdgz=$SIMDIR/$SIMBIN.vcdgz"

mkdir -p $SIMDIR
ghdl -r $GHDLFLAGS $SIMBIN $SIMFLAGS

