#!/usr/bin/env bash

set -eu

SIMDIR="simul"
GHDLFLAGS="--ieee=standard -fsynopsys --warn-no-vital-generic --workdir=$SIMDIR"

COMPONENT="$1"
SIMBIN=$COMPONENT"_tb"

STOPTIME="$2"
SIMFLAGS="--stop-time=$STOPTIME --vcdgz=$SIMDIR/$SIMBIN.vcdgz"

mkdir -p $SIMDIR
ghdl -r $GHDLFLAGS $SIMBIN $SIMFLAGS
